package main

import (
	"github.com/ivpusic/golog"
	"gopkg.in/alecthomas/kingpin.v1"
	"gopkg.in/fsnotify.v1"
	"path/filepath"
	"strconv"
	"strings"
)

var (
	_verbose = kingpin.Flag("verbose", "Verbose mode. It will show internal messages of go-hotreload. Default: false").Short('v').Bool()
	_cmd     = kingpin.Flag("cmd", "Command to execute on each reload. Default: 'go run main.go'").Short('c').String()
	_watch   = kingpin.Flag("watch", "Comma separated list of directories to watch. Default: ['.']").Short('w').String()
	_ignore  = kingpin.Flag("ignore", "Comma separated list of directories to ignore. Default: []").Short('i').String()
	_port    = kingpin.Flag("port", "Port on which app is running. Default: 3000").Short('p').Int()
	_conf    = kingpin.Flag("conf", "Path to json config. Default: ''").String()
	logger   = golog.GetLogger("github.com/ivpusic/go-hotreload/hr")

	cmd     = "go run main.go"
	watch   = []string{"."}
	ignore  = []string{}
	port    = 3000
	verbose = false
)

func contains(arr []string, path string) bool {
	for _, abs := range arr {
		if strings.Index(path, abs) == 0 {
			return true
		}
	}

	return false
}

func main() {
	kingpin.Version("0.0.3")
	kingpin.Parse()

	loadConfiguration()

	watch = convertAbsolutes(watch)
	ignore = convertAbsolutes(ignore)

	pm := processManager{
		port: port,
		cmd:  cmd,
	}

	// if there is old process listening on specified port, kill it
	pm.killOnPort(false)

	logger.Debugf("will run with %q command", pm.cmd)
	logger.Debug("will listen on port " + strconv.Itoa(port))
	for _, val := range watch {
		logger.Debug("watching: " + val)
	}

	for _, val := range ignore {
		logger.Debug("ignoring: " + val)
	}

	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		logger.Panic(err.Error())
	}

	done := make(chan bool)

	// Process events
	go func() {
		for {
			select {
			case ev := <-watcher.Events:
				file := ev.Name
				if strings.HasSuffix(file, ".go") {
					abs, err := filepath.Abs(file)
					if err == nil && contains(watch, abs) && !contains(ignore, abs) {
						logger.Debugf("reloading due to change in file: %q", ev.Name)
						pm.stop()
						pm.run()
					} else {
						logger.Debugf("ignoring change in file: %q", file)
					}
				}
			case err := <-watcher.Errors:
				logger.Errorf("error generated by watcher: %q", err.Error())
				done <- true
			}
		}
	}()

	for _, val := range watch {
		err = watcher.Add(val)
		if err != nil {
			logger.Errorf("error while creating watcher for file %q: %q", val, err.Error())
		}
	}

	pm.run()
	logger.Info("go-hotreload started.")
	logger.Info("Watching for changes.")

	if !verbose {
		logger.Info("Use -v flag for verbose mode")
	}

	<-done
	watcher.Close()
}
